#!/bin/sh

mkdir -p /opt/dbspace
sqlite3 /opt/dbspace/.mida.db < /opt/share/mida_db.sql
rm -rf /opt/share/mida_db.sql

if [ "${USER}" = "root" ]
then
	chown root:root /usr/lib/libaul.so.0.1.0
	chown root:5000 /opt/dbspace/.mida.db
	chown root:5000 /opt/dbspace/.mida.db-journal
fi

chmod 644 /usr/lib/libaul.so.0.1.0
chmod 664 /opt/dbspace/.mida.db
chmod 664 /opt/dbspace/.mida.db-journal

#chmod 1777 /opt/share/miregex	# Set directory to be writable for other accounts
